# Generated by Django 5.1.3 on 2024-11-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cart_unique_together_alter_cart_user_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
