# Generated by Django 5.1.3 on 2024-11-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
